//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallSecuredProxy.EchoServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://echo.services.core.carbon.wso2.org", ConfigurationName="EchoServiceReference.echoSecuredPortType")]
    public interface echoSecuredPortType {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:echoOMElement", ReplyAction="urn:echoOMElementResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CallSecuredProxy.EchoServiceReference.echoOMElementResponse echoOMElement(CallSecuredProxy.EchoServiceReference.echoOMElementRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:echoOMElement", ReplyAction="urn:echoOMElementResponse")]
        System.Threading.Tasks.Task<CallSecuredProxy.EchoServiceReference.echoOMElementResponse> echoOMElementAsync(CallSecuredProxy.EchoServiceReference.echoOMElementRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:echoString", ReplyAction="urn:echoStringResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CallSecuredProxy.EchoServiceReference.echoStringResponse echoString(CallSecuredProxy.EchoServiceReference.echoStringRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:echoString", ReplyAction="urn:echoStringResponse")]
        System.Threading.Tasks.Task<CallSecuredProxy.EchoServiceReference.echoStringResponse> echoStringAsync(CallSecuredProxy.EchoServiceReference.echoStringRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:echoStringArrays", ReplyAction="urn:echoStringArraysResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CallSecuredProxy.EchoServiceReference.echoStringArraysResponse echoStringArrays(CallSecuredProxy.EchoServiceReference.echoStringArraysRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:echoStringArrays", ReplyAction="urn:echoStringArraysResponse")]
        System.Threading.Tasks.Task<CallSecuredProxy.EchoServiceReference.echoStringArraysResponse> echoStringArraysAsync(CallSecuredProxy.EchoServiceReference.echoStringArraysRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:throwAxisFault", ReplyAction="urn:throwAxisFaultResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CallSecuredProxy.EchoServiceReference.throwAxisFaultResponse throwAxisFault(CallSecuredProxy.EchoServiceReference.throwAxisFaultRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:throwAxisFault", ReplyAction="urn:throwAxisFaultResponse")]
        System.Threading.Tasks.Task<CallSecuredProxy.EchoServiceReference.throwAxisFaultResponse> throwAxisFaultAsync(CallSecuredProxy.EchoServiceReference.throwAxisFaultRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:echoInt", ReplyAction="urn:echoIntResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CallSecuredProxy.EchoServiceReference.echoIntResponse echoInt(CallSecuredProxy.EchoServiceReference.echoIntRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:echoInt", ReplyAction="urn:echoIntResponse")]
        System.Threading.Tasks.Task<CallSecuredProxy.EchoServiceReference.echoIntResponse> echoIntAsync(CallSecuredProxy.EchoServiceReference.echoIntRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://echo.services.core.carbon.wso2.org/xsd")]
    public partial class SimpleBean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] a_rField;
        
        private string[] b_rField;
        
        private int cField;
        
        private bool cFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("a_r", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string[] a_r {
            get {
                return this.a_rField;
            }
            set {
                this.a_rField = value;
                this.RaisePropertyChanged("a_r");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("b_r", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string[] b_r {
            get {
                return this.b_rField;
            }
            set {
                this.b_rField = value;
                this.RaisePropertyChanged("b_r");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int c {
            get {
                return this.cField;
            }
            set {
                this.cField = value;
                this.RaisePropertyChanged("c");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cSpecified {
            get {
                return this.cFieldSpecified;
            }
            set {
                this.cFieldSpecified = value;
                this.RaisePropertyChanged("cSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="echoOMElement", WrapperNamespace="http://echo.services.core.carbon.wso2.org", IsWrapped=true)]
    public partial class echoOMElementRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://echo.services.core.carbon.wso2.org", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public object omEle;
        
        public echoOMElementRequest() {
        }
        
        public echoOMElementRequest(object omEle) {
            this.omEle = omEle;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="echoOMElementResponse", WrapperNamespace="http://echo.services.core.carbon.wso2.org", IsWrapped=true)]
    public partial class echoOMElementResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://echo.services.core.carbon.wso2.org", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public object @return;
        
        public echoOMElementResponse() {
        }
        
        public echoOMElementResponse(object @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="echoString", WrapperNamespace="http://echo.services.core.carbon.wso2.org", IsWrapped=true)]
    public partial class echoStringRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://echo.services.core.carbon.wso2.org", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string @in;
        
        public echoStringRequest() {
        }
        
        public echoStringRequest(string @in) {
            this.@in = @in;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="echoStringResponse", WrapperNamespace="http://echo.services.core.carbon.wso2.org", IsWrapped=true)]
    public partial class echoStringResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://echo.services.core.carbon.wso2.org", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string @return;
        
        public echoStringResponse() {
        }
        
        public echoStringResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="echoStringArrays", WrapperNamespace="http://echo.services.core.carbon.wso2.org", IsWrapped=true)]
    public partial class echoStringArraysRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://echo.services.core.carbon.wso2.org", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("a", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] a;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://echo.services.core.carbon.wso2.org", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("b", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] b;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://echo.services.core.carbon.wso2.org", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int c;
        
        public echoStringArraysRequest() {
        }
        
        public echoStringArraysRequest(string[] a, string[] b, int c) {
            this.a = a;
            this.b = b;
            this.c = c;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="echoStringArraysResponse", WrapperNamespace="http://echo.services.core.carbon.wso2.org", IsWrapped=true)]
    public partial class echoStringArraysResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://echo.services.core.carbon.wso2.org", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public CallSecuredProxy.EchoServiceReference.SimpleBean @return;
        
        public echoStringArraysResponse() {
        }
        
        public echoStringArraysResponse(CallSecuredProxy.EchoServiceReference.SimpleBean @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="throwAxisFault", WrapperNamespace="http://echo.services.core.carbon.wso2.org", IsWrapped=true)]
    public partial class throwAxisFaultRequest {
        
        public throwAxisFaultRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="throwAxisFaultResponse", WrapperNamespace="http://echo.services.core.carbon.wso2.org", IsWrapped=true)]
    public partial class throwAxisFaultResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://echo.services.core.carbon.wso2.org", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string @return;
        
        public throwAxisFaultResponse() {
        }
        
        public throwAxisFaultResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="echoInt", WrapperNamespace="http://echo.services.core.carbon.wso2.org", IsWrapped=true)]
    public partial class echoIntRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://echo.services.core.carbon.wso2.org", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @in;
        
        public echoIntRequest() {
        }
        
        public echoIntRequest(int @in) {
            this.@in = @in;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="echoIntResponse", WrapperNamespace="http://echo.services.core.carbon.wso2.org", IsWrapped=true)]
    public partial class echoIntResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://echo.services.core.carbon.wso2.org", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public echoIntResponse() {
        }
        
        public echoIntResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface echoSecuredPortTypeChannel : CallSecuredProxy.EchoServiceReference.echoSecuredPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class echoSecuredPortTypeClient : System.ServiceModel.ClientBase<CallSecuredProxy.EchoServiceReference.echoSecuredPortType>, CallSecuredProxy.EchoServiceReference.echoSecuredPortType {
        
        public echoSecuredPortTypeClient() {
        }
        
        public echoSecuredPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public echoSecuredPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public echoSecuredPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public echoSecuredPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CallSecuredProxy.EchoServiceReference.echoOMElementResponse CallSecuredProxy.EchoServiceReference.echoSecuredPortType.echoOMElement(CallSecuredProxy.EchoServiceReference.echoOMElementRequest request) {
            return base.Channel.echoOMElement(request);
        }
        
        public object echoOMElement(object omEle) {
            CallSecuredProxy.EchoServiceReference.echoOMElementRequest inValue = new CallSecuredProxy.EchoServiceReference.echoOMElementRequest();
            inValue.omEle = omEle;
            CallSecuredProxy.EchoServiceReference.echoOMElementResponse retVal = ((CallSecuredProxy.EchoServiceReference.echoSecuredPortType)(this)).echoOMElement(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CallSecuredProxy.EchoServiceReference.echoOMElementResponse> CallSecuredProxy.EchoServiceReference.echoSecuredPortType.echoOMElementAsync(CallSecuredProxy.EchoServiceReference.echoOMElementRequest request) {
            return base.Channel.echoOMElementAsync(request);
        }
        
        public System.Threading.Tasks.Task<CallSecuredProxy.EchoServiceReference.echoOMElementResponse> echoOMElementAsync(object omEle) {
            CallSecuredProxy.EchoServiceReference.echoOMElementRequest inValue = new CallSecuredProxy.EchoServiceReference.echoOMElementRequest();
            inValue.omEle = omEle;
            return ((CallSecuredProxy.EchoServiceReference.echoSecuredPortType)(this)).echoOMElementAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CallSecuredProxy.EchoServiceReference.echoStringResponse CallSecuredProxy.EchoServiceReference.echoSecuredPortType.echoString(CallSecuredProxy.EchoServiceReference.echoStringRequest request) {
            return base.Channel.echoString(request);
        }
        
        public string echoString(string @in) {
            CallSecuredProxy.EchoServiceReference.echoStringRequest inValue = new CallSecuredProxy.EchoServiceReference.echoStringRequest();
            inValue.@in = @in;
            CallSecuredProxy.EchoServiceReference.echoStringResponse retVal = ((CallSecuredProxy.EchoServiceReference.echoSecuredPortType)(this)).echoString(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CallSecuredProxy.EchoServiceReference.echoStringResponse> CallSecuredProxy.EchoServiceReference.echoSecuredPortType.echoStringAsync(CallSecuredProxy.EchoServiceReference.echoStringRequest request) {
            return base.Channel.echoStringAsync(request);
        }
        
        public System.Threading.Tasks.Task<CallSecuredProxy.EchoServiceReference.echoStringResponse> echoStringAsync(string @in) {
            CallSecuredProxy.EchoServiceReference.echoStringRequest inValue = new CallSecuredProxy.EchoServiceReference.echoStringRequest();
            inValue.@in = @in;
            return ((CallSecuredProxy.EchoServiceReference.echoSecuredPortType)(this)).echoStringAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CallSecuredProxy.EchoServiceReference.echoStringArraysResponse CallSecuredProxy.EchoServiceReference.echoSecuredPortType.echoStringArrays(CallSecuredProxy.EchoServiceReference.echoStringArraysRequest request) {
            return base.Channel.echoStringArrays(request);
        }
        
        public CallSecuredProxy.EchoServiceReference.SimpleBean echoStringArrays(string[] a, string[] b, int c) {
            CallSecuredProxy.EchoServiceReference.echoStringArraysRequest inValue = new CallSecuredProxy.EchoServiceReference.echoStringArraysRequest();
            inValue.a = a;
            inValue.b = b;
            inValue.c = c;
            CallSecuredProxy.EchoServiceReference.echoStringArraysResponse retVal = ((CallSecuredProxy.EchoServiceReference.echoSecuredPortType)(this)).echoStringArrays(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CallSecuredProxy.EchoServiceReference.echoStringArraysResponse> CallSecuredProxy.EchoServiceReference.echoSecuredPortType.echoStringArraysAsync(CallSecuredProxy.EchoServiceReference.echoStringArraysRequest request) {
            return base.Channel.echoStringArraysAsync(request);
        }
        
        public System.Threading.Tasks.Task<CallSecuredProxy.EchoServiceReference.echoStringArraysResponse> echoStringArraysAsync(string[] a, string[] b, int c) {
            CallSecuredProxy.EchoServiceReference.echoStringArraysRequest inValue = new CallSecuredProxy.EchoServiceReference.echoStringArraysRequest();
            inValue.a = a;
            inValue.b = b;
            inValue.c = c;
            return ((CallSecuredProxy.EchoServiceReference.echoSecuredPortType)(this)).echoStringArraysAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CallSecuredProxy.EchoServiceReference.throwAxisFaultResponse CallSecuredProxy.EchoServiceReference.echoSecuredPortType.throwAxisFault(CallSecuredProxy.EchoServiceReference.throwAxisFaultRequest request) {
            return base.Channel.throwAxisFault(request);
        }
        
        public string throwAxisFault() {
            CallSecuredProxy.EchoServiceReference.throwAxisFaultRequest inValue = new CallSecuredProxy.EchoServiceReference.throwAxisFaultRequest();
            CallSecuredProxy.EchoServiceReference.throwAxisFaultResponse retVal = ((CallSecuredProxy.EchoServiceReference.echoSecuredPortType)(this)).throwAxisFault(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CallSecuredProxy.EchoServiceReference.throwAxisFaultResponse> CallSecuredProxy.EchoServiceReference.echoSecuredPortType.throwAxisFaultAsync(CallSecuredProxy.EchoServiceReference.throwAxisFaultRequest request) {
            return base.Channel.throwAxisFaultAsync(request);
        }
        
        public System.Threading.Tasks.Task<CallSecuredProxy.EchoServiceReference.throwAxisFaultResponse> throwAxisFaultAsync() {
            CallSecuredProxy.EchoServiceReference.throwAxisFaultRequest inValue = new CallSecuredProxy.EchoServiceReference.throwAxisFaultRequest();
            return ((CallSecuredProxy.EchoServiceReference.echoSecuredPortType)(this)).throwAxisFaultAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CallSecuredProxy.EchoServiceReference.echoIntResponse CallSecuredProxy.EchoServiceReference.echoSecuredPortType.echoInt(CallSecuredProxy.EchoServiceReference.echoIntRequest request) {
            return base.Channel.echoInt(request);
        }
        
        public int echoInt(int @in) {
            CallSecuredProxy.EchoServiceReference.echoIntRequest inValue = new CallSecuredProxy.EchoServiceReference.echoIntRequest();
            inValue.@in = @in;
            CallSecuredProxy.EchoServiceReference.echoIntResponse retVal = ((CallSecuredProxy.EchoServiceReference.echoSecuredPortType)(this)).echoInt(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CallSecuredProxy.EchoServiceReference.echoIntResponse> CallSecuredProxy.EchoServiceReference.echoSecuredPortType.echoIntAsync(CallSecuredProxy.EchoServiceReference.echoIntRequest request) {
            return base.Channel.echoIntAsync(request);
        }
        
        public System.Threading.Tasks.Task<CallSecuredProxy.EchoServiceReference.echoIntResponse> echoIntAsync(int @in) {
            CallSecuredProxy.EchoServiceReference.echoIntRequest inValue = new CallSecuredProxy.EchoServiceReference.echoIntRequest();
            inValue.@in = @in;
            return ((CallSecuredProxy.EchoServiceReference.echoSecuredPortType)(this)).echoIntAsync(inValue);
        }
    }
}
