//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallProxyApplication.echoService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://echo.services.core.carbon.wso2.org", ConfigurationName="echoService.echoPortType")]
    public interface echoPortType {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:echoOMElement", ReplyAction="urn:echoOMElementResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CallProxyApplication.echoService.echoOMElementResponse echoOMElement(CallProxyApplication.echoService.echoOMElementRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:echoOMElement", ReplyAction="urn:echoOMElementResponse")]
        System.Threading.Tasks.Task<CallProxyApplication.echoService.echoOMElementResponse> echoOMElementAsync(CallProxyApplication.echoService.echoOMElementRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:throwAxisFault", ReplyAction="urn:throwAxisFaultResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CallProxyApplication.echoService.throwAxisFaultResponse throwAxisFault(CallProxyApplication.echoService.throwAxisFaultRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:throwAxisFault", ReplyAction="urn:throwAxisFaultResponse")]
        System.Threading.Tasks.Task<CallProxyApplication.echoService.throwAxisFaultResponse> throwAxisFaultAsync(CallProxyApplication.echoService.throwAxisFaultRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:echoInt", ReplyAction="urn:echoIntResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CallProxyApplication.echoService.echoIntResponse echoInt(CallProxyApplication.echoService.echoIntRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:echoInt", ReplyAction="urn:echoIntResponse")]
        System.Threading.Tasks.Task<CallProxyApplication.echoService.echoIntResponse> echoIntAsync(CallProxyApplication.echoService.echoIntRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:echoStringArrays", ReplyAction="urn:echoStringArraysResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CallProxyApplication.echoService.echoStringArraysResponse echoStringArrays(CallProxyApplication.echoService.echoStringArraysRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:echoStringArrays", ReplyAction="urn:echoStringArraysResponse")]
        System.Threading.Tasks.Task<CallProxyApplication.echoService.echoStringArraysResponse> echoStringArraysAsync(CallProxyApplication.echoService.echoStringArraysRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:echoString", ReplyAction="urn:echoStringResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CallProxyApplication.echoService.echoStringResponse echoString(CallProxyApplication.echoService.echoStringRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:echoString", ReplyAction="urn:echoStringResponse")]
        System.Threading.Tasks.Task<CallProxyApplication.echoService.echoStringResponse> echoStringAsync(CallProxyApplication.echoService.echoStringRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://echo.services.core.carbon.wso2.org/xsd")]
    public partial class SimpleBean : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] a_rField;
        
        private string[] b_rField;
        
        private int cField;
        
        private bool cFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("a_r", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string[] a_r {
            get {
                return this.a_rField;
            }
            set {
                this.a_rField = value;
                this.RaisePropertyChanged("a_r");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("b_r", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string[] b_r {
            get {
                return this.b_rField;
            }
            set {
                this.b_rField = value;
                this.RaisePropertyChanged("b_r");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int c {
            get {
                return this.cField;
            }
            set {
                this.cField = value;
                this.RaisePropertyChanged("c");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cSpecified {
            get {
                return this.cFieldSpecified;
            }
            set {
                this.cFieldSpecified = value;
                this.RaisePropertyChanged("cSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="echoOMElement", WrapperNamespace="http://echo.services.core.carbon.wso2.org", IsWrapped=true)]
    public partial class echoOMElementRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://echo.services.core.carbon.wso2.org", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public object omEle;
        
        public echoOMElementRequest() {
        }
        
        public echoOMElementRequest(object omEle) {
            this.omEle = omEle;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="echoOMElementResponse", WrapperNamespace="http://echo.services.core.carbon.wso2.org", IsWrapped=true)]
    public partial class echoOMElementResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://echo.services.core.carbon.wso2.org", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public object @return;
        
        public echoOMElementResponse() {
        }
        
        public echoOMElementResponse(object @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="throwAxisFault", WrapperNamespace="http://echo.services.core.carbon.wso2.org", IsWrapped=true)]
    public partial class throwAxisFaultRequest {
        
        public throwAxisFaultRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="throwAxisFaultResponse", WrapperNamespace="http://echo.services.core.carbon.wso2.org", IsWrapped=true)]
    public partial class throwAxisFaultResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://echo.services.core.carbon.wso2.org", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string @return;
        
        public throwAxisFaultResponse() {
        }
        
        public throwAxisFaultResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="echoInt", WrapperNamespace="http://echo.services.core.carbon.wso2.org", IsWrapped=true)]
    public partial class echoIntRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://echo.services.core.carbon.wso2.org", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @in;
        
        public echoIntRequest() {
        }
        
        public echoIntRequest(int @in) {
            this.@in = @in;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="echoIntResponse", WrapperNamespace="http://echo.services.core.carbon.wso2.org", IsWrapped=true)]
    public partial class echoIntResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://echo.services.core.carbon.wso2.org", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public echoIntResponse() {
        }
        
        public echoIntResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="echoStringArrays", WrapperNamespace="http://echo.services.core.carbon.wso2.org", IsWrapped=true)]
    public partial class echoStringArraysRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://echo.services.core.carbon.wso2.org", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("a", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] a;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://echo.services.core.carbon.wso2.org", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("b", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] b;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://echo.services.core.carbon.wso2.org", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int c;
        
        public echoStringArraysRequest() {
        }
        
        public echoStringArraysRequest(string[] a, string[] b, int c) {
            this.a = a;
            this.b = b;
            this.c = c;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="echoStringArraysResponse", WrapperNamespace="http://echo.services.core.carbon.wso2.org", IsWrapped=true)]
    public partial class echoStringArraysResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://echo.services.core.carbon.wso2.org", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public CallProxyApplication.echoService.SimpleBean @return;
        
        public echoStringArraysResponse() {
        }
        
        public echoStringArraysResponse(CallProxyApplication.echoService.SimpleBean @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="echoString", WrapperNamespace="http://echo.services.core.carbon.wso2.org", IsWrapped=true)]
    public partial class echoStringRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://echo.services.core.carbon.wso2.org", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string @in;
        
        public echoStringRequest() {
        }
        
        public echoStringRequest(string @in) {
            this.@in = @in;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="echoStringResponse", WrapperNamespace="http://echo.services.core.carbon.wso2.org", IsWrapped=true)]
    public partial class echoStringResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://echo.services.core.carbon.wso2.org", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string @return;
        
        public echoStringResponse() {
        }
        
        public echoStringResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface echoPortTypeChannel : CallProxyApplication.echoService.echoPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class echoPortTypeClient : System.ServiceModel.ClientBase<CallProxyApplication.echoService.echoPortType>, CallProxyApplication.echoService.echoPortType {
        
        public echoPortTypeClient() {
        }
        
        public echoPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public echoPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public echoPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public echoPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CallProxyApplication.echoService.echoOMElementResponse CallProxyApplication.echoService.echoPortType.echoOMElement(CallProxyApplication.echoService.echoOMElementRequest request) {
            return base.Channel.echoOMElement(request);
        }
        
        public object echoOMElement(object omEle) {
            CallProxyApplication.echoService.echoOMElementRequest inValue = new CallProxyApplication.echoService.echoOMElementRequest();
            inValue.omEle = omEle;
            CallProxyApplication.echoService.echoOMElementResponse retVal = ((CallProxyApplication.echoService.echoPortType)(this)).echoOMElement(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CallProxyApplication.echoService.echoOMElementResponse> CallProxyApplication.echoService.echoPortType.echoOMElementAsync(CallProxyApplication.echoService.echoOMElementRequest request) {
            return base.Channel.echoOMElementAsync(request);
        }
        
        public System.Threading.Tasks.Task<CallProxyApplication.echoService.echoOMElementResponse> echoOMElementAsync(object omEle) {
            CallProxyApplication.echoService.echoOMElementRequest inValue = new CallProxyApplication.echoService.echoOMElementRequest();
            inValue.omEle = omEle;
            return ((CallProxyApplication.echoService.echoPortType)(this)).echoOMElementAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CallProxyApplication.echoService.throwAxisFaultResponse CallProxyApplication.echoService.echoPortType.throwAxisFault(CallProxyApplication.echoService.throwAxisFaultRequest request) {
            return base.Channel.throwAxisFault(request);
        }
        
        public string throwAxisFault() {
            CallProxyApplication.echoService.throwAxisFaultRequest inValue = new CallProxyApplication.echoService.throwAxisFaultRequest();
            CallProxyApplication.echoService.throwAxisFaultResponse retVal = ((CallProxyApplication.echoService.echoPortType)(this)).throwAxisFault(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CallProxyApplication.echoService.throwAxisFaultResponse> CallProxyApplication.echoService.echoPortType.throwAxisFaultAsync(CallProxyApplication.echoService.throwAxisFaultRequest request) {
            return base.Channel.throwAxisFaultAsync(request);
        }
        
        public System.Threading.Tasks.Task<CallProxyApplication.echoService.throwAxisFaultResponse> throwAxisFaultAsync() {
            CallProxyApplication.echoService.throwAxisFaultRequest inValue = new CallProxyApplication.echoService.throwAxisFaultRequest();
            return ((CallProxyApplication.echoService.echoPortType)(this)).throwAxisFaultAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CallProxyApplication.echoService.echoIntResponse CallProxyApplication.echoService.echoPortType.echoInt(CallProxyApplication.echoService.echoIntRequest request) {
            return base.Channel.echoInt(request);
        }
        
        public int echoInt(int @in) {
            CallProxyApplication.echoService.echoIntRequest inValue = new CallProxyApplication.echoService.echoIntRequest();
            inValue.@in = @in;
            CallProxyApplication.echoService.echoIntResponse retVal = ((CallProxyApplication.echoService.echoPortType)(this)).echoInt(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CallProxyApplication.echoService.echoIntResponse> CallProxyApplication.echoService.echoPortType.echoIntAsync(CallProxyApplication.echoService.echoIntRequest request) {
            return base.Channel.echoIntAsync(request);
        }
        
        public System.Threading.Tasks.Task<CallProxyApplication.echoService.echoIntResponse> echoIntAsync(int @in) {
            CallProxyApplication.echoService.echoIntRequest inValue = new CallProxyApplication.echoService.echoIntRequest();
            inValue.@in = @in;
            return ((CallProxyApplication.echoService.echoPortType)(this)).echoIntAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CallProxyApplication.echoService.echoStringArraysResponse CallProxyApplication.echoService.echoPortType.echoStringArrays(CallProxyApplication.echoService.echoStringArraysRequest request) {
            return base.Channel.echoStringArrays(request);
        }
        
        public CallProxyApplication.echoService.SimpleBean echoStringArrays(string[] a, string[] b, int c) {
            CallProxyApplication.echoService.echoStringArraysRequest inValue = new CallProxyApplication.echoService.echoStringArraysRequest();
            inValue.a = a;
            inValue.b = b;
            inValue.c = c;
            CallProxyApplication.echoService.echoStringArraysResponse retVal = ((CallProxyApplication.echoService.echoPortType)(this)).echoStringArrays(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CallProxyApplication.echoService.echoStringArraysResponse> CallProxyApplication.echoService.echoPortType.echoStringArraysAsync(CallProxyApplication.echoService.echoStringArraysRequest request) {
            return base.Channel.echoStringArraysAsync(request);
        }
        
        public System.Threading.Tasks.Task<CallProxyApplication.echoService.echoStringArraysResponse> echoStringArraysAsync(string[] a, string[] b, int c) {
            CallProxyApplication.echoService.echoStringArraysRequest inValue = new CallProxyApplication.echoService.echoStringArraysRequest();
            inValue.a = a;
            inValue.b = b;
            inValue.c = c;
            return ((CallProxyApplication.echoService.echoPortType)(this)).echoStringArraysAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CallProxyApplication.echoService.echoStringResponse CallProxyApplication.echoService.echoPortType.echoString(CallProxyApplication.echoService.echoStringRequest request) {
            return base.Channel.echoString(request);
        }
        
        public string echoString(string @in) {
            CallProxyApplication.echoService.echoStringRequest inValue = new CallProxyApplication.echoService.echoStringRequest();
            inValue.@in = @in;
            CallProxyApplication.echoService.echoStringResponse retVal = ((CallProxyApplication.echoService.echoPortType)(this)).echoString(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CallProxyApplication.echoService.echoStringResponse> CallProxyApplication.echoService.echoPortType.echoStringAsync(CallProxyApplication.echoService.echoStringRequest request) {
            return base.Channel.echoStringAsync(request);
        }
        
        public System.Threading.Tasks.Task<CallProxyApplication.echoService.echoStringResponse> echoStringAsync(string @in) {
            CallProxyApplication.echoService.echoStringRequest inValue = new CallProxyApplication.echoService.echoStringRequest();
            inValue.@in = @in;
            return ((CallProxyApplication.echoService.echoPortType)(this)).echoStringAsync(inValue);
        }
    }
}
